<?php

$students=array(
	array(
		"cordell",
		"durand",
		"playing bass",
		"This is one paragraph. Well, it's not really a paragraph, but this is a sample anyway.",
		"So I guess this is another one.",
		"And this is a third one.",
		"Favorite Songs to Play Bass On",
		"One Song",
		"Two Song",
		"Three Song",
		"Four Song",
		"Five Song",
		"Six Song",
		"Seven Song",
		"Eight Song",
		"Nine Song",
		"Ten Song",
		"PHP-izzle!",
		"I learned how to do PHP in this class. Yay!",
		"twitter.com/lazyrivr",
		"facebook.com",
		"",
		"www.andy-bell.com/blog/",
		"youtube.com/user/lazyrivr",
		"mormon.org",
		"files.andy-bell.com/310sample/cordelldurand",
		"cdpic1.jpg",
		"pic2.jpg",
		"pic3cd.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		102,
		105,
		200
	),
	array(
		"jude",
		"thatcher",
		"being british",
		"This is one paragraph. Well, it's not really a paragraph, but this is a sample anyway.",
		"So I guess this is another one.",
		"And this is a third one.",
		"Favorite British Things",
		"One British Thing",
		"Two British Thing",
		"Three British Thing",
		"Four British Thing",
		"Five British Thing",
		"Six British Thing",
		"Seven British Thing",
		"Eight British Thing",
		"Nine British Thing",
		"Ten British Thing",
		"CSS Artistry!",
		"I learned how to do practically paint with CSS. Yay!",
		"",
		"facebook.com",
		"linkedin.com",
		"www.andy-bell.com/blog/",
		"",
		"mormon.org",
		"files.andy-bell.com/310sample/judethatcher",
		"jtpic1.jpg",
		"pic2.jpg",
		"pic3jt.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		55,
		123,
		12
	),
	array(
		"lambert",
		"atkinson",
		"sheeple",
		"This is one paragraph. Well, it's not really a paragraph, but this is a sample anyway.",
		"So I guess this is another one.",
		"And this is a third one.",
		"Favorite Ways the Man Gets You Down",
		"One Way",
		"Two Way",
		"Three Way",
		"Four Way",
		"Five Way",
		"Six Way",
		"Seven Way",
		"Eight Way",
		"Nine Way",
		"Ten Way",
		"HTML Sucks",
		"It's so structured. Just like the man wants you to be. Boo!",
		"",
		"",
		"",
		"www.andy-bell.com/blog/",
		"youtube.com/user/lazyrivr",
		"",
		"files.andy-bell.com/310sample/lambertatkinson",
		"lapic1.jpg",
		"pic2.jpg",
		"pic3la.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		0,
		0,
		255
	),
	array(
		"willis",
		"harrell",
		"action stardom",
		"This is one paragraph. Well, it's not really a paragraph, but this is a sample anyway.",
		"So I guess this is another one.",
		"See what I'm doing here? Willis? Bruce Willis? Hahaha.",
		"Favorite Ways to Die Hard",
		"One Die Hard",
		"Two Die Hard",
		"Three Die Hard",
		"Four Die Hard",
		"Five Die Hard",
		"Six Die Hard",
		"Seven Die Hard",
		"Eight Die Hard",
		"Nine Die Hard",
		"How many of these will there be?",
		"Procrastination",
		"The action hero never saves the day until the last minute. That's why I did all my projects at the last minute too!",
		"twitter.com/lazyrivr",
		"facebook.com",
		"linkedin.com",
		"www.andy-bell.com/blog/",
		"youtube.com/user/lazyrivr",
		"mormon.org",
		"files.andy-bell.com/310sample/willisharrell",
		"whpic1.jpg",
		"pic2.jpg",
		"pic3wh.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		23,
		57,
		91
	),
	array(
		"lester",
		"forrest",
		"now I'm streching for stuff",
		"This is one paragraph. Well, it's not really a paragraph, but this is a sample anyway.",
		"So I guess this is another one.",
		"And this is a third one.",
		"Favorite Trees",
		"One Tree",
		"Two Tree",
		"Three Tree",
		"Four Tree",
		"Five Tree",
		"Six Tree",
		"Seven Tree",
		"Eight Tree",
		"Nine Tree",
		"Ten Tree",
		"No more dead trees!",
		"Now that I know how to make digital media stuff, I can stop using paper-based things!",
		"twitter.com/lazyrivr",
		"facebook.com",
		"",
		"",
		"",
		"mormon.org",
		"files.andy-bell.com/310sample/lesterforrest",
		"lfpic1.jpg",
		"pic2.jpg",
		"pic3lf.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		32,
		32,
		32
	),
	array(
		"nigel",
		"hancock",
		"being british?",
		"Wait. That one's taken. Nigel's a good australian name too! So I guess I'm that.",
		"So I guess this is another one.",
		"And this is a third one.",
		"Favorite Prisoners I'm Decended From",
		// Nothing but love for the Aussies! I've just met some very prideful ones and it's fun to reference Austrailia's prison colony days when they get too prideful!
		"One Prisoner",
		"Two Prisoner",
		"Three Prisoner",
		"Four Prisoner",
		"Five Prisoner",
		"Six Prisoner",
		"Seven Prisoner",
		"Eight Prisoner",
		"Nine Prisoner",
		"Ten Prisoner",
		"CSS Artistry, Mate!",
		"I learned how to paint ferociously with CSS, just like a crocodile. Yay!",
		"twitter.com/lazyrivr",
		"facebook.com",
		"",
		"www.andy-bell.com/blog/",
		"",
		"mormon.org",
		"files.andy-bell.com/310sample/nigelhancock",
		"nhpic1.jpg",
		"pic2.jpg",
		"pic3nh.jpg",
		"This is one photo.",
		"This is a second photo.",
		"This is a third photo.",
		48,
		42,
		200
	)
);

?>